openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Closer backend"
  description: "Our ambitious project"
servers:
  - url: "http://localhost:3000"
    description: "Default local environment"
#components:
  #securitySchemes:
    ##See https://demo.identityserver.io/ for configuration details.
    #identity_server_auth:
      #type: oauth2
      #flows:
        #implicit:
          #authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          #scopes:
            #api: "api"
security:
  - identity_server_auth:
    - api

components:
  headers:
    x-auth-token:
      description: User session token
      schema:
        type: string
      example: 2pgH65A742a4Raw45OVcOYsmea5LtpAjSNTtPWaLxxQ=